const products = [
  {
    id: 1,
    image: "images/shoe1.jpg",
    name: "SAGE",
    category: "SHOES",
    price: 80,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 2,
    image: "images/shoe2.jpg",
    name: "ADIDAS",
    category: "SHOES",
    price: 1000,
    description: "soluta ipsam autem eius necessitatibus fugiat",
  },
  {
    id: 3,
    image: "images/shoe3.jpg",
    name: "PUMA",
    category: "SHOES",
    price: 399,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 4,
    image: "images/cloths.jpg",
    name: "PRADA",
    category: "CLOTHES",
    price: 120,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 5,
    image: "images/cap1.jpg",
    name: "Flexfit",
    category: "CAPS",
    price: 40,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 6,
    image: "images/cap2.jpg",
    name: "Goorin Bros",
    category: "CAPS",
    price: 30,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 7,
    image: "images/cloths2.jpg",
    name: "Rabbins",
    category: "CLOTHES",
    price: 600,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
  {
    id: 8,
    image: "images/cloths3.jpg",
    name: "Jugers",
    category: "CLOTHES",
    price: 300,
    description: "soluta ipsam autem eius necessitatibus fugiat in.",
  },
];

export default products;
